use crate::config::Config;
use std::fs;
use std::path::Path;

/// The adapter scripts ride inside the binary so a bare `goulash` needs no
/// checkout and no manual .zshrc edits.
const ZSH_SCRIPT: &str = include_str!("../shell/goulash.zsh");
const BASH_SCRIPT: &str = include_str!("../shell/goulash.bash");

pub struct Integration {
    pub argv: Vec<String>,
    pub envs: Vec<(String, String)>,
}

fn passthrough(argv: Vec<String>) -> Integration {
    Integration {
        argv,
        envs: Vec::new(),
    }
}

/// Auto-inject shell integration for known shells launched with plain
/// flags. Anything unusual (custom args, unknown shell, no config dir)
/// passes through untouched — manual sourcing still works there.
pub fn prepare(argv: Vec<String>, auto: bool) -> Integration {
    if !auto {
        return passthrough(argv);
    }
    let shell = Path::new(&argv[0])
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_string();
    let plain_flags = argv[1..]
        .iter()
        .all(|a| matches!(a.as_str(), "-i" | "-l" | "--login"));
    if !plain_flags {
        return passthrough(argv);
    }
    let Some(dir) = Config::dir() else {
        return passthrough(argv);
    };
    match shell.as_str() {
        "zsh" => match zsh_envs(&dir) {
            Some(envs) => Integration { argv, envs },
            None => passthrough(argv),
        },
        "bash" => prepare_bash(argv, &dir),
        _ => passthrough(argv),
    }
}

/// Write the zdot stubs and return the env overrides, or None on any
/// filesystem trouble (caller falls back to passthrough).
fn zsh_envs(dir: &Path) -> Option<Vec<(String, String)>> {
    let shell_dir = dir.join("shell");
    let zdot = dir.join("zdot");
    fs::create_dir_all(&shell_dir).ok()?;
    fs::create_dir_all(&zdot).ok()?;
    fs::write(shell_dir.join("goulash.zsh"), ZSH_SCRIPT).ok()?;

    let adapter = shell_dir.join("goulash.zsh");
    let zshenv = "\
# generated by goulash; do not edit\n\
__gz=\"${GOULASH_ORIG_ZDOTDIR:-$HOME}\"\n\
[[ -f \"$__gz/.zshenv\" ]] && builtin source \"$__gz/.zshenv\"\n\
unset __gz\n";
    let zprofile = "\
# generated by goulash; do not edit\n\
__gz=\"${GOULASH_ORIG_ZDOTDIR:-$HOME}\"\n\
[[ -f \"$__gz/.zprofile\" ]] && builtin source \"$__gz/.zprofile\"\n\
unset __gz\n";
    let zshrc = format!(
        "# generated by goulash; do not edit\n\
         if [[ -n \"$GOULASH_ORIG_ZDOTDIR\" ]]; then\n\
         \x20\x20ZDOTDIR=\"$GOULASH_ORIG_ZDOTDIR\"\n\
         \x20\x20unset GOULASH_ORIG_ZDOTDIR\n\
         else\n\
         \x20\x20ZDOTDIR=\"$HOME\"\n\
         fi\n\
         [[ -f \"$ZDOTDIR/.zshrc\" ]] && builtin source \"$ZDOTDIR/.zshrc\"\n\
         builtin source {}\n",
        shq(&adapter.display().to_string())
    );
    fs::write(zdot.join(".zshenv"), zshenv).ok()?;
    fs::write(zdot.join(".zprofile"), zprofile).ok()?;
    fs::write(zdot.join(".zshrc"), zshrc).ok()?;

    let mut envs = vec![("ZDOTDIR".to_string(), zdot.display().to_string())];
    if let Ok(orig) = std::env::var("ZDOTDIR") {
        envs.push(("GOULASH_ORIG_ZDOTDIR".to_string(), orig));
    }
    Some(envs)
}

fn prepare_bash(argv: Vec<String>, dir: &Path) -> Integration {
    let shell_dir = dir.join("shell");
    if fs::create_dir_all(&shell_dir).is_err() {
        return passthrough(argv);
    }
    let adapter = shell_dir.join("goulash.bash");
    if fs::write(&adapter, BASH_SCRIPT).is_err() {
        return passthrough(argv);
    }
    let rcfile = shell_dir.join("bashrc");
    let rc = format!(
        "# generated by goulash; do not edit\n\
         [ -f \"$HOME/.bashrc\" ] && source \"$HOME/.bashrc\"\n\
         source {}\n",
        shq(&adapter.display().to_string())
    );
    if fs::write(&rcfile, rc).is_err() {
        return passthrough(argv);
    }
    let mut new_argv = vec![
        argv[0].clone(),
        "--rcfile".to_string(),
        rcfile.display().to_string(),
    ];
    new_argv.extend(argv[1..].iter().cloned());
    Integration {
        argv: new_argv,
        envs: Vec::new(),
    }
}

/// Single-quote for shell sourcing (paths may contain spaces).
fn shq(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}
