use crate::config::Config;
use std::fs;
use std::path::Path;

/// The adapter scripts ride inside the binary so a bare `goulash` needs no
/// checkout and no manual .zshrc edits.
const ZSH_SCRIPT: &str = include_str!("../shell/goulash.zsh");
const BASH_SCRIPT: &str = include_str!("../shell/goulash.bash");

pub struct Integration {
    pub argv: Vec<String>,
    pub envs: Vec<(String, String)>,
}

fn passthrough(argv: Vec<String>) -> Integration {
    Integration {
        argv,
        envs: Vec::new(),
    }
}

/// Auto-inject shell integration for known shells launched with plain
/// flags. Anything unusual (custom args, unknown shell, no config dir)
/// passes through untouched — manual sourcing still works there.
pub fn prepare(argv: Vec<String>, auto: bool) -> Integration {
    if !auto {
        return passthrough(argv);
    }
    let shell = Path::new(&argv[0])
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_string();
    let plain_flags = argv[1..]
        .iter()
        .all(|a| matches!(a.as_str(), "-i" | "-l" | "--login"));
    if !plain_flags {
        return passthrough(argv);
    }
    let Some(dir) = Config::dir() else {
        return passthrough(argv);
    };
    match shell.as_str() {
        "zsh" => match zsh_envs(&dir) {
            Some(envs) => Integration { argv, envs },
            None => passthrough(argv),
        },
        "bash" => prepare_bash(argv, &dir),
        _ => passthrough(argv),
    }
}

/// Write the zdot stubs and return the env overrides, or None on any
/// filesystem trouble (caller falls back to passthrough).
fn zsh_envs(dir: &Path) -> Option<Vec<(String, String)>> {
    let shell_dir = dir.join("shell");
    let zdot = dir.join("zdot");
    fs::create_dir_all(&shell_dir).ok()?;
    fs::create_dir_all(&zdot).ok()?;
    fs::write(shell_dir.join("goulash.zsh"), ZSH_SCRIPT).ok()?;

    let adapter = shell_dir.join("goulash.zsh");
    // ZDOTDIR has to keep pointing at our dir so zsh finds the next stub
    // — but the user's own file must see the value it would have seen
    // without us, because `fpath+=$ZDOTDIR/functions` in a .zshenv is a
    // completely ordinary thing to write. So it is swapped around each
    // source and swapped straight back.
    let stage = |file: &str| {
        format!(
            "# generated by goulash; do not edit\n\
             __gz_ours=\"$ZDOTDIR\"\n\
             if [[ -n \"$GOULASH_ORIG_ZDOTDIR\" ]]; then\n\
             \x20\x20ZDOTDIR=\"$GOULASH_ORIG_ZDOTDIR\"\n\
             else\n\
             \x20\x20builtin unset ZDOTDIR\n\
             fi\n\
             __gz=\"${{ZDOTDIR:-$HOME}}\"\n\
             [[ -f \"$__gz/{file}\" ]] && builtin source \"$__gz/{file}\"\n\
             ZDOTDIR=\"$__gz_ours\"\n\
             builtin unset __gz __gz_ours\n"
        )
    };
    // .zshrc is the last stub: it restores ZDOTDIR for good, which is
    // also what makes a login shell read the user's own .zlogin and
    // .zlogout natively — zsh expands $ZDOTDIR afresh for each startup
    // file, so no stub is needed for either.
    let zshrc = format!(
        "# generated by goulash; do not edit\n\
         if [[ -n \"$GOULASH_ORIG_ZDOTDIR\" ]]; then\n\
         \x20\x20ZDOTDIR=\"$GOULASH_ORIG_ZDOTDIR\"\n\
         \x20\x20builtin unset GOULASH_ORIG_ZDOTDIR\n\
         else\n\
         \x20\x20builtin unset ZDOTDIR\n\
         fi\n\
         [[ -f \"${{ZDOTDIR:-$HOME}}/.zshrc\" ]] \\\n\
         \x20\x20&& builtin source \"${{ZDOTDIR:-$HOME}}/.zshrc\"\n\
         builtin source {}\n",
        shq(&adapter.display().to_string())
    );
    fs::write(zdot.join(".zshenv"), stage(".zshenv")).ok()?;
    fs::write(zdot.join(".zprofile"), stage(".zprofile")).ok()?;
    fs::write(zdot.join(".zshrc"), zshrc).ok()?;

    let mut envs = vec![("ZDOTDIR".to_string(), zdot.display().to_string())];
    if let Ok(orig) = std::env::var("ZDOTDIR") {
        envs.push(("GOULASH_ORIG_ZDOTDIR".to_string(), orig));
    }
    Some(envs)
}

fn prepare_bash(argv: Vec<String>, dir: &Path) -> Integration {
    let shell_dir = dir.join("shell");
    if fs::create_dir_all(&shell_dir).is_err() {
        return passthrough(argv);
    }
    let adapter = shell_dir.join("goulash.bash");
    if fs::write(&adapter, BASH_SCRIPT).is_err() {
        return passthrough(argv);
    }
    // bash ignores --rcfile for LOGIN shells: it reads /etc/profile and
    // then the first of ~/.bash_profile, ~/.bash_login, ~/.profile, and
    // nothing we can name. Verified — `bash -l -i --rcfile X` reads
    // neither X nor ~/.bashrc. There is no --profile-file to point at
    // either, so the only way to reach a login bash is to drop the login
    // flag and reproduce that startup sequence ourselves, in order,
    // before the adapter.
    let login = argv[1..]
        .iter()
        .any(|a| matches!(a.as_str(), "-l" | "--login"));
    let rcfile = shell_dir.join("bashrc");
    let rc = if login {
        format!(
            "# generated by goulash; do not edit\n\
             # login-shell emulation: bash cannot be told where to find a\n\
             # profile, so goulash replays the sequence it would have used.\n\
             [ -r /etc/profile ] && . /etc/profile\n\
             for __gz in \"$HOME/.bash_profile\" \"$HOME/.bash_login\" \
             \"$HOME/.profile\"; do\n\
             \x20\x20if [ -r \"$__gz\" ]; then . \"$__gz\"; break; fi\n\
             done\n\
             unset __gz\n\
             . {}\n",
            shq(&adapter.display().to_string())
        )
    } else {
        format!(
            "# generated by goulash; do not edit\n\
             [ -f \"$HOME/.bashrc\" ] && . \"$HOME/.bashrc\"\n\
             . {}\n",
            shq(&adapter.display().to_string())
        )
    };
    if fs::write(&rcfile, rc).is_err() {
        return passthrough(argv);
    }
    let mut new_argv = vec![
        argv[0].clone(),
        "--rcfile".to_string(),
        rcfile.display().to_string(),
    ];
    // Keep -i; drop the login flag we are standing in for, or bash goes
    // back to ignoring the rcfile entirely.
    new_argv.extend(
        argv[1..]
            .iter()
            .filter(|a| !matches!(a.as_str(), "-l" | "--login"))
            .cloned(),
    );
    if login && !new_argv.iter().any(|a| a == "-i") {
        new_argv.push("-i".to_string());
    }
    Integration {
        argv: new_argv,
        envs: Vec::new(),
    }
}

/// Single-quote for shell sourcing (paths may contain spaces).
fn shq(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}
